import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import "@/styles/globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";

export const metadata: Metadata = {
  title: "Welcome",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: '/delivery-bike.png', type: 'image/png' },
    ]
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body>
        <AntdRegistry>
          <ConfigProvider theme={{ hashed: false, token: { fontFamily: "Quantico" } }}>
            {children}
          </ConfigProvider>
        </AntdRegistry>
        <Toaster />
      </body>
    </html>
  );
}
